function see_closure(vPath,erica_data)
% Plots data generated by 'find_cosure.m'



%% Load data file

% Prompt for directory
if nargin < 1
   [vPath] = uigetdir(pwd,'Choose video directory');
end

% Prompt if data file is present
if isempty(dir([vPath filesep 'profile_data.mat']))
    error('No profile_data.mat file in chosen directory')
    
else
    load([vPath filesep 'profile_data.mat']);
    
end


%% Plot results 

figure

% Plot closure data
h1 = plot(p.time,p.closed);
xlabel('Time (s)')
ylim([-.1 1.1])
xlim([0 1.1*max(p.time)])
set(gca,'YTick',[0 1])
text(max(p.time)*1.02,0,'open')
text(max(p.time)*1.02,1,'closed')

% If erica data provided, overlay onto plot
if nargin > 1
    hold on
    plot(erica_data(:,1),erica_data(:,2),'r')
    legend('matlab','erica')
    hold off
end
    

