function calcMechanics
% Uses the morph data generated by acquire.m and visualize.m to calculate 
% mechanical parameters necessary to mathematically model the mechanics of 
% the appendage


%% Prompt for the filename of data to be analyzed

% [fileName,dataPath,fIndex]  = uigetfile('*.*','Choose a data file');
% if ~fIndex, return, end


dataPath = '/Volumes/Docs/Projects/Patek_project/morpho_images/data';
fileName = 'californiensis.mat';

[fileName,filePath,fileExt] = giveFileParts(fileName,dataPath);
load([filePath])




ttt=3;











%% FUNCTIONS


function [fileName,filePath,fileExt] = giveFileParts(fileName,pathh)

tmp = find(fileName=='.');

if length(tmp)>1
    error('You cannot have periods in the filename');
elseif length(tmp)<1
    error('Your filename needs an extension')
end

fileExt  = fileName(tmp:end);
fileName = fileName(1:tmp-1);
filePath = [pathh filesep fileName fileExt];



function morph = cylinderData
